// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZU3vt4YRcptL1yCeHfUYzcIbei-JoCtM',
    appId: '1:571099536831:web:45f027318be6212c6dd50a',
    messagingSenderId: '571099536831',
    projectId: 'pavanhitechagro-60c49',
    authDomain: 'pavanhitechagro-60c49.firebaseapp.com',
    storageBucket: 'pavanhitechagro-60c49.firebasestorage.app',
    measurementId: 'G-2S6XRS1S6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5fSChynHnQGhK9DTmmhpV3LWcTGVBAUM',
    appId: '1:571099536831:android:3858bc306ac4f2d36dd50a',
    messagingSenderId: '571099536831',
    projectId: 'pavanhitechagro-60c49',
    storageBucket: 'pavanhitechagro-60c49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzx1zcrKiRYWLaUzPeyuSTcShjt4zp8ak',
    appId: '1:571099536831:ios:6eae564950658fda6dd50a',
    messagingSenderId: '571099536831',
    projectId: 'pavanhitechagro-60c49',
    storageBucket: 'pavanhitechagro-60c49.firebasestorage.app',
    iosBundleId: 'com.example.agriApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzx1zcrKiRYWLaUzPeyuSTcShjt4zp8ak',
    appId: '1:571099536831:ios:6eae564950658fda6dd50a',
    messagingSenderId: '571099536831',
    projectId: 'pavanhitechagro-60c49',
    storageBucket: 'pavanhitechagro-60c49.firebasestorage.app',
    iosBundleId: 'com.example.agriApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZU3vt4YRcptL1yCeHfUYzcIbei-JoCtM',
    appId: '1:571099536831:web:9ac070973165626a6dd50a',
    messagingSenderId: '571099536831',
    projectId: 'pavanhitechagro-60c49',
    authDomain: 'pavanhitechagro-60c49.firebaseapp.com',
    storageBucket: 'pavanhitechagro-60c49.firebasestorage.app',
    measurementId: 'G-906JYM9VGB',
  );
}
